language: python

python:
  - "2.7"

env:
  - DJANGO=django==1.5.4

install:
  - "pip install --upgrade setuptools --use-mirrors"
  - "pip install $DJANGO --use-mirrors"
  - "pip install --use-mirrors --allow-all-external --allow-unverified django-admin-tools -r requirements.txt"
  - "pip install Pillow --use-mirrors"
  - "touch onepercentclub/settings/secrets.py"

before_script:
  - npm install

script:
  - python ./manage.py test --settings=onepercentclub.settings.travis -v 0
  - grunt travis # add --force to overlook JS test failures
