language: python

python:
  # - "2.6.5" # fails to activate virtualenv...
  - "2.7"

env:
  - DJANGO=django==1.5.4
  - DJANGO=https://github.com/django/django/archive/master.zip

install:
  - "pip install --upgrade setuptools --use-mirrors"
  - "pip install $DJANGO --use-mirrors"
  - "pip install --use-mirrors --allow-all-external --allow-unverified django-admin-tools -r requirements.txt"
  - "pip install Pillow --use-mirrors"
  - "touch onepercentclub/settings/secrets.py"

matrix:
  allow_failures:
    - env: DJANGO=https://github.com/django/django/archive/master.zip

before_script:
  - npm install

script:
  - python ./manage.py test --settings=onepercentclub.settings.travis -v 1
  - grunt travis --verbose # add --force to overlook JS test failures
