language: python

python:
  - "2.7"

node_js:
  - "0.10"

addons:
  firefox: "26.0"

env:
  - DJANGO=django==1.5.4

install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "pip install --upgrade setuptools --use-mirrors"
  - "pip install $DJANGO --use-mirrors"
  - "pip install --use-mirrors --allow-all-external --allow-unverified django-admin-tools -r requirements/ci_requirements.txt"
  - "pip install Pillow --use-mirrors"
  - "touch onepercentclub/settings/secrets.py"
  
before_script:
  - "pip show bluebottle"
  - "grunt compass:dist --bb_path=\"`pip show bluebottle | grep Location | cut -b11-`/bluebottle/common/static/sass\""

script:
  - python ./manage.py test --settings=onepercentclub.settings.travis -v 1
  # - grunt travis --verbose # add --force to pass build on JS failures
